SELECT
	`tr`.`ct_id` AS `ct_id`,
	`tr`.`date` AS `date`,
	`tr`.`type` AS `type`,
	`tr`.`effectuated` AS `effectuated`,
	`tr`.`researcher` AS `researcher`,
	`tr`.`comment` AS `comment`,
	`tr`.`found_registry` AS `found_registry`,
	`tr`.`completion_date` AS `completion_date`,
	`tr`.`lawfirm` AS `lawfirm`,
	`tr`.`multi_cbm` AS `multi_cbm`,
	`tr`.`negotiation_body` AS `negotiation_body`,
	`tr`.`bler` AS `bler`,
	`t1`.`name` AS `name`,
	`t1`.`employee_number` AS `employee_number`,
	`t1`.`year_employee` AS `year_employee`,
	`t1`.`total_employee_number_eu` AS `total_employee_number_eu`,
	`t1`.`total_employee_number_ww` AS `total_employee_number_ww`,
	`t1`.`year_total_employee` AS `year_total_employee`,
	`t1`.`diverging_employee_number` AS `diverging_employee_number`,
	`t1`.`year_diverging_employee` AS `year_diverging_employee`,
	`t1`.`company_form` AS `company_form`,
	`t1`.`ac_listed` AS `ac_listed`,
	`t1`.`sector` AS `sector`,
	`t1`.`nace_code` AS `nace_code`,
	`t1`.`nat_registration_number` AS `nat_registration_number`,
	`t1`.`board_structure` AS `board_structure`,
	`t1`.`tnic` AS `tnic`,
	`t1`.`ewc` AS `ewc`,
	`t1`.`intl_bler` AS `intl_bler`,
	`t1`.`company_website` AS `company_website`,
	`t1`.`parent_name` AS `parent_name`,
	`t1`.`ac_location` AS `ac_location`,
	`t1`.`ac_iso` AS `ac_iso`,
	`t2`.`mc_name` AS `mc_name`,
	`t2`.`memployee_number` AS `memployee_number`,
	`t2`.`myear_employee` AS `myear_employee`,
	`t2`.`mcompany_form` AS `mcompany_form`,
	`t2`.`mnace_code` AS `mnace_code`,
	`t2`.`mnat_registration_number` AS `mnat_registration_number`,
	`t2`.`msector` AS `msector`,
	`t2`.`mc_location` AS `mc_location`,
	`t2`.`mc_iso` AS `mc_iso`
FROM ((`transaction` `tr`
		JOIN (
			SELECT
				`ac`.`ac_id` AS `a_id`,
				`ac`.`ac_id` AS `ac_id`,
				`ac`.`name` AS `name`,
				`ac`.`employee_number` AS `employee_number`,
				`ac`.`year_employee` AS `year_employee`,
				`ac`.`total_employee_number_eu` AS `total_employee_number_eu`,
				`ac`.`total_employee_number_ww` AS `total_employee_number_ww`,
				`ac`.`year_total_employee` AS `year_total_employee`,
				`ac`.`diverging_employee_number` AS `diverging_employee_number`,
				`ac`.`year_diverging_employee` AS `year_diverging_employee`,
				`ac`.`company_form` AS `company_form`,
				`ac`.`ac_listed` AS `ac_listed`,
				`ac`.`sector` AS `sector`,
				`ac`.`nace_code` AS `nace_code`,
				`ac`.`nat_registration_number` AS `nat_registration_number`,
				`ac`.`board_structure` AS `board_structure`,
				`ac`.`tnic` AS `tnic`,
				`ac`.`ewc` AS `ewc`,
				`ac`.`intl_bler` AS `intl_bler`,
				`ac`.`p_id` AS `p_id`,
				`ac`.`company_website` AS `company_website`,
				`p`.`name` AS `parent_name`,
				`l`.`name` AS `ac_location`,
				`l`.`iso_id` AS `ac_iso`
			FROM (((`acquiring_company` `ac`
						JOIN `ac_locations` `al` ON ((`ac`.`ac_id` = `al`.`ac_id`)))
					JOIN `location` `l` ON ((`al`.`Location_id` = `l`.`id`)))
				JOIN `parent_company` `p` ON ((`ac`.`p_id` = `p`.`p_id`)))) `t1` ON ((`tr`.`Acquiring_company_ac_id` = `t1`.`a_id`)))
	JOIN (
		SELECT
			`mc`.`mc_id` AS `m_id`,
			`mc`.`name` AS `mc_name`,
			`mc`.`employee_number` AS `memployee_number`,
			`mc`.`year_employee` AS `myear_employee`,
			`mc`.`company_form` AS `mcompany_form`,
			`mc`.`nace_code` AS `mnace_code`,
			`mc`.`nat_registration_number` AS `mnat_registration_number`,
			`mc`.`sector` AS `msector`,
			`l`.`name` AS `mc_location`,
			`l`.`iso_id` AS `mc_iso`
		FROM ((`merging_company` `mc`
				JOIN `mc_locations` `ml` ON ((`mc`.`mc_id` = `ml`.`mc_id`)))
			JOIN `location` `l` ON ((`ml`.`Location_id` = `l`.`id`)))) `t2` ON ((`tr`.`Merging_company_mc_id` = `t2`.`m_id`)));